server:
  port: 8082

spring:
  application:
    name: notification-service

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
    from: ${SMTP_USERNAME:}

notification:
  email:
    enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
    mock: ${NOTIFICATION_EMAIL_MOCK:true}